### ISSUE TITLE
[Bug]: Studio: Pivot Options Do Not Work

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#10003]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Various options for pivot should change where the gizmo is for the selected objects

### What happened?

Pivot options do not work.

### Steps to reproduce

```shell
1. In the studio, select a 3D model where the mesh is off center
2. Try changing the pivot options, nothing will happen
```

**Comment by SYBIOTE** [comment]
wait pivots are only for multiple entities right?

**Comment by SYBIOTE** [comment]
presently pivots only work for manipulating multiple selected objects with the transform gizmo
