### ISSUE TITLE
[Bug]: Adding Collider Component to Entity in Studio Does Not Generate a Collider

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#10005]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

When a collider component is added to an entity, it should immediately generate a collider in Rapier which corresponds to the component parameters

### What happened?

No collider is generated when the component is added

### Steps to reproduce

```shell
1. In the studio, create an entity and add a collider component to it
2. No collider appears
```

**Comment by HexaField** [comment]
Is the expectation here that adding a collider would automatically add a rigidbody if one doesn't exist on the entity or an ancestor?
