### ISSUE TITLE
[Bug]: Local Dev: Authentication Stalls

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#10010]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

On local dev, authentication should be essentially instant, because the client is also the local machine

### What happened?

On local dev, every page except the default URL (localhost:3000) stalls on authentication indefinitely.
On the default URL, authentication takes upwards of 5 minutes on many occasions

### Steps to reproduce

```shell
1. on local dev run `npm run dev`
2. try to access any page in the studio
3. authentication step hangs forever, except on the default page
4. on the default page, authentication hangs for minutes at a time
```

**Comment by HexaField** [comment]
try switch to local storage instead of minio, should speed it up considerably
