### ISSUE TITLE
[Epic]: Studio Simple/Advanced Mode Switch

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#10018]
### Functionality

File menu
- New Scene
- Save Scene
- Save Scene As
- Copy Scene to Project

Scene Management
 - prefabs abstration over components for foolproof object creation

Asset panel (library)
- View kits
  - Add asset to hierarchy
- View imported assets
  - Import assert
    - Imported asset settings
      - Compression
      - LOD
  - Materials
    - Drag & drop from library
    - Open material editor
- Basic object properties
- Search & filters

Preview
- Placement
- Grid/snapping

Play mode
- Publish Project
- Publish to Location

Tasks
- [x] #10033
- [x] #10034

## Advanced Mode
 todo - everything as per full designs

**Comment by SYBIOTE** [comment]
hmm, so a new UI section entirely, the mode likely goes into EditorState, so we are reviving prefabs?

**Comment by HexaField** [comment]
> so we are reviving prefabs?

yeah pretty much!

**Comment by zeek0123** [comment]
Whats the difference between preview and play ?

**Comment by HexaField** [comment]
> Whats the difference between preview and play ?

Preview is previewing an asset for placing in a scene, like a lot of 3d editors, a transparent copy of the asset appears that follows the pointer.

Play mode spawns an avatar into the scene.
