### ISSUE TITLE
[Bug]: Modified component serialization issues

### ISSUE THREAD

**Issue by SamMazerIR** [ir-engine/etherealengine-archive#10024]
### Version

8d9e94c541467eae704c171244a9fb7b534476f8

### Operating Systems

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### Browser (if applicable)

Chrome

### What is supposed happened?

When adding serialized information to your component through your custom NodeEditor inputs (e.g. ColorInput field, TextInput field, etc.) if you have already added your component to an entity new fields should serialize properly as you add them

### What happened?

When adding serialized information to your component through your custom NodeEditor inputs (e.g. ColorInput field, TextInput field, etc.) if you have already added your component to an entity it will not update/serialize properly. 

You'll know you're in this state because the json for the component's props will be null.
This will lead to issues in setting the values, potentially initializing the value on load (if you're attempting to load from json) and may throw errors when assigning information (e.g. from a color picker selection)

### Steps to reproduce

```shell
create a new component type and associated node editor. add your component to an entity in your scene and save.

once this is done, add data to your component and expose them with inputs from your node editor. make sure you add associated `onSet` and `toJson` to your component
```

**Comment by HexaField** [comment]
which component did this happen for?

**Comment by SamMazerIR** [comment]
> which component did this happen for?

this was a custom component I was developing. I think it's a fairly reasonable workflow that leads you to this issue (create a component, add to scene, keep adding to component/node editor).

It's easy enough to work around (delete your entity and remake it with your component) but if you're unaware of what is happening the errors you get don't help much to identify the root cause

**Comment by HexaField** [comment]
interesting, theres a few variables that could be at play here. i'd have to look through the code you wrote to see exactly what could be happening

**Comment by SamMazerIR** [comment]
> interesting, theres a few variables that could be at play here. i'd have to look through the code you wrote to see exactly what could be happening

you can repro this with any new component that has an editor accessible value if you follow my repro steps in the ticket. It isn't so much about the specific code but the order in which you do the actions. Daniel is also already looking into this I think
