### ISSUE TITLE
[Bug]: Lighting stopped working

### ISSUE THREAD

**Issue by MbfloydIR** [ir-engine/etherealengine-archive#10040]
### Version

6df1116cedb7c8eb03b955bc2ce01e79e99bb1f2

### Operating Systems

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### Browser (if applicable)

Chrome

### What is supposed happened?

Lighting with Shadows

### What happened?

No lighting / shadows, everything is grey
<img width="1205" alt="image" src="https://github.com/EtherealEngine/etherealengine/assets/144718558/90e8a8c7-5716-4ad7-9a3d-c3e75345ef2b">

### Steps to reproduce

```shell
Add primitive cubes to a new scenes.
Add the shadow component to them.
```

**Comment by HexaField** [comment]
fixed https://github.com/EtherealEngine/etherealengine/pull/10080
