### ISSUE TITLE
[Bug]: Misc Issues with project permission

### ISSUE THREAD

**Issue by hanzlamateen** [ir-engine/etherealengine-archive#10115]
Following are the various issues

1. It seems like currently duplicate entries for project permission with same projectId and userId can exist.
2. Also, it seems like file-browser service does not check for project permissions from editor.
3. Also, we need to see how project-permission of guest impacts the access he has in the system (i.e. editor, etc)

**Comment by HexaField** [comment]
Guests should never have access to the studio. Any user must have an oauth to receive project permissions.
