### ISSUE TITLE
[Bug]: Linking Portals Broken

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9600]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Should be able to link a portal to an existing portal in the same scene or another scene

### What happened?

setting location ID seems to be broken:
[Screencast from 01-10-2024 08:04:35 AM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/8d6129f4-d6a5-459a-b060-dcb9e406b194)

### Steps to reproduce

```shell
1. In a studio scene, create a portal. Save that scene
2. Create a location for that scene
3. In a different scene, add another portal
4. Try to link the portal to the first portal
5. The location id does not populate and cannot be manually input
6. Make a second location from this scene
6. Try going to the second location and walking through the portal. You will be redirected to location "" no matter what location the linked portal is in
```

**Comment by HexaField** [comment]
Just needed to replace ControlledStringInput with StringInput
