### ISSUE TITLE
[Bug]: Updating Directional Light Properties Lost on Next Snapshot

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9601]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Should update lights and have the values commit

### What happened?

[Screencast from 01-10-2024 08:44:16 AM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/06af7d19-0a53-45de-a5ba-cf7396c3fdab)

### Steps to reproduce

```shell
1. Open a scene in studio
2. Adjust the intensity of directional light
3. Click on something else in the scene
4. Light will be reset to old intensity
```

**Comment by HexaField** [comment]
Sovled. The scrubber had the wrong prop for onRelease - it ws onCommit. It's now standardized.
