### ISSUE TITLE
[Bug]: Pressing enter in hierarchy search causes page redirect

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9689]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Not applicable

### What happened?

[Screencast from 01-30-2024 02:12:30 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/cc60102c-bd68-449e-8942-b2377d25770c)

### Steps to reproduce

```shell
press enter in the hierarchy panel search bar
```

**Comment by SYBIOTE** [comment]
cannot reproduce

**Comment by SYBIOTE** [comment]
fixed

**Comment by SYBIOTE** [comment]
@HexaField , @dinomut1
