### ISSUE TITLE
[Bug]: Material library crashes UI whenever selected material is disposed

### ISSUE THREAD

**Issue by AidanCaruso** [ir-engine/etherealengine-archive#9694]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Not applicable

### What happened?

UI crashes due to error below
![image](https://github.com/EtherealEngine/etherealengine/assets/102248647/048f51e2-bb3d-4ac9-b286-8e0f9fb9b919)
![image](https://github.com/EtherealEngine/etherealengine/assets/102248647/84870bf7-90bc-4077-8b8f-5aafc6a73ed1)
looks like the material library may be attempting to access a material that has been disposed.

### Steps to reproduce

```shell
Any action that removes the material libarary's currently selected material, including
- Switching scenes with a material selected
- Removing the entity with the model component that the selected material is sourced from
```

**Comment by dinomut1** [comment]
This is fixed in the [Material Assets Fix](https://github.com/EtherealEngine/etherealengine/pull/9664) PR. Basically it deselects the material when it is disposed
