### ISSUE TITLE
[Bug]: Renaming Entities in Studio Broken

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9756]
### Version

0f27df2(1.5.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Renaming entities in studio should work

### What happened?

Renaming entities does not work

### Steps to reproduce

```shell
In the studio, try to rename an entity in the hierarchy panel. The name field will not update when you commit the change in the name text input field
```

**Comment by HexaField** [comment]
fixed https://github.com/EtherealEngine/etherealengine/commit/cae4331dea7bdcba8b0339ddfc842261ab281bcb
