### ISSUE TITLE
[Bug]: Reparenting Broken in Studio

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9850]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Not applicable

### What happened?

Reparent causes UI to go blank, need to close and re-open to see that the reparent has occurred, but all descendants of the newly reparented model are missing.
[Screencast from 03-06-2024 05:07:29 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/a956e430-b6a0-42a5-ba67-ed3f652f4c11)

### Steps to reproduce

```shell
For UI bug, reparent anything in the hierarchy panel. When reparenting a model, the geo will be missing
```

**Comment by SYBIOTE** [comment]
its the properties panel, when reparenting for a brief moment the properties panel loses context as the entity id changes for the reparented entity, thus causing a block

**Comment by SYBIOTE** [comment]
this is fixed
