### ISSUE TITLE
Standardize on lower case for project naming & ensure repo matches package json name

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9869]
As a short term bandaid until the big project refactor is done

**Comment by barankyle** [comment]
Why do we want to force the repo name to match the package.json name? I'm sure 99% of the time people will do it and it'll make the most sense, but is there a downside to being able to save the project 'testproject' in the repo 'ee-testproject'?

**Comment by HexaField** [comment]
> Why do we want to force the repo name to match the package.json name? I'm sure 99% of the time people will do it and it'll make the most sense, but is there a downside to being able to save the project 'testproject' in the repo 'ee-testproject'?

if memory serves i'm pretty sure it's necessary for imports to make sense, i think we've run into problems when the package.json name was not matching the folder name in case

**Comment by barankyle** [comment]
Looking at the code, I don't believe the repo name is used for the local file path, that comes from project.name.

**Comment by HexaField** [comment]
> Looking at the code, I don't believe the repo name is used for the local file path, that comes from project.name.

What is the source of truth for the folder that is imported in the project import helpers in /packages/projects, for the system, webappinjection & worldinjection imports?

**Comment by HexaField** [comment]
Resolved - repo name and package json currently does not need to be matching. Will consider in the future again for `@<orgName>/<repoName>` namespacing
