### ISSUE TITLE
[Bug]: Rotation Gizmo Not Working

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9908]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Not applicable

### What happened?

[Screencast from 03-13-2024 03:55:45 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/6d6fcc14-be6b-4cb5-aac0-1e3696f5a7bf)

### Steps to reproduce

```shell
Try to rotate anything using gizmo. Not correctly registering mouse hover, and click and drag doesn't register either
```

**Comment by SYBIOTE** [comment]
this is fixed closing this
