### ISSUE TITLE
Add kill floor height to scene settings

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9910]
- [x] add kill floor number value to SceneSettingsComponent
- [x] In a new pre-physics simulation group system for the kill floor, iterate through each SceneSettingsComponent and then iterate the query for `[RigidbodyComponent, Not(RigidbodyFixedTagComponent), NetworkAuthorityTagComponent]` and if the rigidbody y value is below the kill floor, teleport the rigidbody back to it's SpawnPoseState position & rotation by setting & dirtying the TransfromComponent

**Comment by SYBIOTE** [comment]
using the not from bitecs
