### ISSUE TITLE
Optimize asset-only projects to not be downloaded for rebuild

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9928]
A lot of our projects don't have any code. We should move the non-code APIs from the `xrengine.config.ts` to the `package.json` for the project, and only have an `xrengine.config.ts` for projects that have code assets. Following this, we can optimize the build process accordingly.

**Comment by barankyle** [comment]
Add a boolean in the project schema for asset-only, dependent on whether or not an xrengine.config.ts file is present. install-projects.js can skip downloading the project if the flag indicates it's asset-only.

**Comment by barankyle** [comment]
Move thumbnail link from xrengine.config.ts to package.json (etherealengine section of package.json), so that asset-only projects can still have a thumbnail.
