### ISSUE TITLE
[Bug]: `./scripts/tailscalecerts.sh` fails

### ISSUE THREAD

**Issue by the-reality-engineer** [ir-engine/etherealengine-archive#9948]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Generate tailscale certificates, placing them in the certs/tailscale folder, which is git-ignored. 

Ideally, modify .env.local with necessary changes. 

### What happened?

The tailscalecerts.sh script ends up dumping some cert files directly in the root of the repo, where it is tracked by git. This seems incorrect. 

Also, it forces me to use sudo which seems to break the script (no certs generated). The script only generates certificaters (and places them at the root of the repo) when I don't use sudo. 

### Steps to reproduce

```shell
Run the script on macOS, using the Mac App Store app variant of the Tailscale installation.
```

**Comment by DanielBelmes** [comment]
Completed. Mac os wanted some specific permissions and I made one typo
