### ISSUE TITLE
BrowserFS Deprecated

### ISSUE THREAD

**Issue by james-pre** [ir-engine/etherealengine-archive#9980]
Hi there, I'm a maintainer of BrowserFS. I've been going though the [dependents](https://www.npmjs.com/package/browserfs?activeTab=dependents) of BrowserFS.

Please see the notice in the readme: https://github.com/jvilk/browserfs

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

**Comment by HexaField** [comment]
@james-pre  Thank you! Seems we addressed this and never got back to you.
