### ISSUE TITLE
Replace in-line usage of UUID generation for entity UUIDs with a helper function

### ISSUE THREAD

**Issue by HexaField** [ir-engine/etherealengine-archive#9988]
We have a few different sources of UUID generation (MathUtils.generateUUID, uuidv4 etc) that result in different formats for UUIDs. We should standardize on the best source of randomness & uniqueness between them and add a helper function `generateEntityUUID()` that uses it and returns it typed as `EntityUUID`

**Comment by DanielBelmes** [comment]
going with uuid package so we can remove some more dependencies on three.js :)
