### ISSUE TITLE
[Bug]: Assets Panel: Drag and Drop Broken

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9992]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Dragging and dropping a gltf or other asset from the assets panel should place an instance of that asset in the scene where the mouse is released

### What happened?

Drag and drop is a no-op

### Steps to reproduce

```shell
1. drag and drop anything from the assets panel
2. nothing happens
```

**Comment by SYBIOTE** [comment]
working in local dev

**Comment by SYBIOTE** [comment]
in deploy dev, noticing the URL returns 404 error.

its working properly for the assets I can see in the admin resource panel.

the question is why is there a disconnect between the assets panel and the file storage

**Comment by SYBIOTE** [comment]
still works, in dev deploy, im closing this
