### ISSUE TITLE
[Bug]: Assets Panel has "unknown" shelf category which crashes engine on click

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9993]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Categories should be able to be selected in the assets panel to bring up a list of the assets under that category

### What happened?

In the Assets Panel, there is an "unknown" category at the bottom of the list. If you click on it, the engine crashes
[Screencast from 03-26-2024 06:30:39 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/1a61f703-f173-4b1c-90f7-3cc3f56d3eb6)

### Steps to reproduce

```shell
Go to the assets panel and click on the "unknown" category
```

**Comment by Rezmason** [comment]
Resolved by filtering out any folder in the panel whose asset class is "unknown".
