### ISSUE TITLE
[Bug]: Reparenting a 3D Model Causes Duplicates in Material Library

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9995]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Reparenting a model in the scene should change nothing about the material library, nor should it trigger a reload of the model

### What happened?

Reparenting a model causes it to attempt a reload, but in an incomplete manner, which generates duplicate material library entries

### Steps to reproduce

```shell
1. In the studio, reparent any model 
2. Observe the duplicates in the material library
```

**Comment by SYBIOTE** [comment]
i suspect it was causes by the allComponents remove quietly failed , this was resolved by @DanielBelmes , and its merged in already

**Comment by SYBIOTE** [comment]
i dont see this issue in dev deployed anymore

**Comment by SYBIOTE** [comment]
closing this issue
