### ISSUE TITLE
[Bug]: Drag and Drop Places Object Below Ground Plane

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9996]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Dragging and dropping an asset should place it on top of the ground plane

### What happened?

Drag and drop places the asset below the ground plane
[Screencast from 03-26-2024 06:43:50 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/cf8e3d68-2807-4e11-92af-74d1d83bf4a1)

Using this asset:
[integrated-collider-test.zip](https://github.com/EtherealEngine/etherealengine/files/14765357/integrated-collider-test.zip)

### Steps to reproduce

```shell
1. In the studio, make a new blank scene
2. Unzip, then drag and drop the cube provided above into a scene
3. The cube appears below the ground plane
```

**Comment by SYBIOTE** [comment]
i am cosistently seeing it beign place above gorund plane, i think it depends on the camera position

**Comment by SYBIOTE** [comment]
cannot reproduce, closing the issue
