### ISSUE TITLE
[Bug]: When Gizmo is Active, Cannot Click on Anything Else

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9998]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Should be able to click on anything in the scene to select it

### What happened?

When the gizmo is active in the studio, user is unable to click on anything else in the scene to select. Clicks become no-ops

### Steps to reproduce

```shell
1. In studio, click on something to bring up the gizmo
2. Try to click on anything else in the scene to change selection
3. Selection does not change and clicks are no-ops
```

**Comment by SYBIOTE** [comment]
yeah thats a known issue, its because of how i prgrammed the heuristics, ill come up with something better
