### ISSUE TITLE
[Bug]: On Studio Load, First Click Instantly Rotates camera 45 Degrees Downward

### ISSUE THREAD

**Issue by dinomut1** [ir-engine/etherealengine-archive#9999]
### Version

08c3b70(1.6.0)

### Operating Systems

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### What is supposed happened?

Camera should not move if user performs a click on the screen

### What happened?

When a studio scene is first loaded, the first click on the scene itself will instantly rotate the camera downward. 

### Steps to reproduce

```shell
1. Open any scene in the studio
2. Left click on the scene
3. Camera will rotate downward instantly
```

**Comment by SYBIOTE** [comment]
looks like the cause of this when you click on the scene after load, it focuses on the scene object first, the scene object is at origin, so camera focuses on the origin

**Comment by SYBIOTE** [comment]
@dinomut1 , what would you suggest as a possible solution , maybe we dont allow the scene root entity to be selected?

**Comment by HexaField** [comment]
> @dinomut1 , what would you suggest as a possible solution , maybe we dont allow the scene root entity to be selected?

We just need to be recalculating the orbit camera, there is a boolean on it, just need to trigger it at the right time.
